### ISSUE TITLE
self-hosted-runner による CD を実現したい

### ISSUE THREAD

**Issue by SawadaReverse** [SawadaReverse/sake-club-on-discord#4]
現状

<details><summary>deploy.yml</summary>

```yml
name: deploy

on:
  push:
    branches:
      - main

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHANNEL_NAME: ${{ vars.CHANNEL_NAME }}
  LOG_LEVEL: ${{ vars.LOG_LEVEL }}
  TORIKI_COMMAND: ${{ vars.TORIKI_COMMAND }}

jobs:
  deploy:
    name: deploy
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy
        run: docker compose up -d --force-recreate
```
</details>

- 環境変数を docker compose が受け取れているかもわからん
- 仮に受け取れていたとして、ビルド時に環境変数が渡されているかわからん
- 少なくとも実行時には環境変数がなく、build が通っても実行できずに終わってしまう
- docker build --build-args で指定する方法に変えても良いかもしれないが、そうすると .env で指定しているときのラクさがなくなってしまう
